### ISSUE TITLE
Build error on ArchLinux

### ISSUE THREAD

**Issue by hk3f** [devlopersabbir/any-video-downloader-chrome-extension#1]
Host: Linux FarchNB 6.3.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 20:46:20 +0000 x86_64 GNU/Linux
npm version: 9.7.2
local/nodejs 20.3.0-1

Build error for npm run build step:
> app@0.0.0 build
> tsc && vite build

src/App.tsx:26:10 - error TS6133: 'platform' is declared but its value is never read.

26   const [platform, setPlatform] = useState<string>("");
            ~~~~~~~~

src/App.tsx:26:20 - error TS6133: 'setPlatform' is declared but its value is never read.

26   const [platform, setPlatform] = useState<string>("");
                      ~~~~~~~~~~~

Found 2 errors in the same file, starting at: src/App.tsx:26

**Comment by hk3f** [comment]
Also some error when running npi i at app directory:
`npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @crxjs/vite-plugin@1.0.14
npm ERR! Found: vite@4.3.5
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.3.2" from the root project
npm ERR!   peer vite@"^4.2.0" from @vitejs/plugin-react@4.0.0
npm ERR!   node_modules/@vitejs/plugin-react
npm ERR!     dev @vitejs/plugin-react@"^4.0.0" from the root project
npm ERR!     optional @vitejs/plugin-react@">=1.2.0" from @crxjs/vite-plugin@1.0.14
npm ERR!     node_modules/@crxjs/vite-plugin
npm ERR!       dev @crxjs/vite-plugin@"^1.0.14" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.9.0" from @crxjs/vite-plugin@1.0.14
npm ERR! node_modules/@crxjs/vite-plugin
npm ERR!   dev @crxjs/vite-plugin@"^1.0.14" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vite@2.9.16
npm ERR! node_modules/vite
npm ERR!   peer vite@"^2.9.0" from @crxjs/vite-plugin@1.0.14
npm ERR!   node_modules/@crxjs/vite-plugin
npm ERR!     dev @crxjs/vite-plugin@"^1.0.14" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
`

**Comment by devlopersabbir** [comment]
thanks for your valuable information... I'll try to fix all of the issue very soon
